# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('token_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=66)),
            ],
        ),
    ]
