# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180407_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.BooleanField(default=False),
        ),
    ]
