# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180408_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_turn',
            field=models.IntegerField(default=2),
        ),
    ]
