# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_game_player_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ctime',
            field=models.IntegerField(default=60),
        ),
    ]
