# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_game_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
