# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_game_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='over',
            field=models.CharField(default='no', max_length=255),
        ),
    ]
