# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_game_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
