# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default='Draw', max_length=255),
        ),
    ]
